version: '1'
services:
  react:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react-app.rule=Host(`localhost`)"
      - "traefik.http.routers.react-app.entrypoints=web"
      - "traefik.http.services.react-app.loadbalancer.server.port=80"
    expose:
      - "80"

  traefik:
    image: "traefik:3.1"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"